# Copyright Verizon Media. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
shared:
  annotations:
    screwdriver.cd/restrictPR: fork

jobs:
  publish:
    requires: [~pr, ~commit]
    image: docker.io/almalinux:9
    secrets:
      - DOCKER_HUB_DEPLOY_KEY

    annotations:
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
      screwdriver.cd/disk: HIGH
      screwdriver.cd/timeout: 30

    environment:
      USER_SHELL_BIN: bash
      CONTAINER_IMAGE: "docker.io/vespaengine/vespa-pipeline"
      CONTAINER_TAG: "latest"

    steps:
      - inspect: |
          set -x
          env | grep -v TOKEN
          cat /proc/cpuinfo
          cat /proc/meminfo
          df -h
          uname -a

      - install-deps: |
          dnf install -y dnf-plugins-core
          dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          dnf install -y --allowerasing docker-ce-cli

      - build-and-publish: |
          if [[ -z $SD_PULL_REQUEST ]]; then
            set +x
            docker login -u aressem -p $DOCKER_HUB_DEPLOY_KEY
            set -x
            DOCKER_BUILDX_PUSH="--push"
          fi

          docker info
          docker version
          docker buildx version
          docker buildx install

          unset DOCKER_HOST
          docker context create vespa-context --docker "host=tcp://localhost:2376,ca=/certs/client/ca.pem,cert=/certs/client/cert.pem,key=/certs/client/key.pem"
          docker context use vespa-context
          docker buildx create --name vespa-builder --driver docker-container --use
          docker buildx inspect --bootstrap
          docker buildx build --progress plain $DOCKER_BUILDX_PUSH --platform linux/amd64,linux/arm64 --tag $CONTAINER_IMAGE:$CONTAINER_TAG .

      - teardown-inspect: |
          docker image ls
          df -h
